Packet
Space-Enterprise-at-Berkeley/Ground-Station pull request #11
Opened 2020-09-27 06:14 UTC by evelynliu16

Finished packet.py file which decodes the message into a packet object.

2020-09-28 02:41 UTC, fazerlicourice7 requested changes
Very small changes, but overall looks great!

2020-09-28 02:41 UTC, fazerlicourice7 commented on packet.py
> +        checksum_data = data[i + 1:tracker]
You should go from `1: tracker` since the checksum includes the sensor id

2020-09-28 02:41 UTC, fazerlicourice7 commented on packet.py
> +        data = [int(data[i]) for i in range(len(data))]
it could be floats.

2020-09-29 00:28 UTC, vamshiBalanaga commented
Can we also add an `encode_packet` func that takes in the sensor id and an array of floats and calculates the checksum and returns a string packet

2020-10-09 00:57 UTC, fazerlicourice7 requested changes
Can the encode just be added to the same Packet class? I don't see why there should be two of them. just allow us to create it with either the packet string or the raw initial data.

2020-10-10 19:32 UTC, fazerlicourice7 requested changes

2020-10-10 19:32 UTC, fazerlicourice7 commented on packet.py
> +        self.checksum = checksum
Move these into `encode_data` and here, just call encode data with the right parameters.
Add a string variable that holds the encoded message so after I create a packet instance with 
```
packet = Packet(3, {23, 43, 5})
packet.encoded_message
```

2020-10-14 01:24 UTC, fazerlicourice7 approved these changes

2020-10-14 01:25 UTC, merged